DROP TABLE IF EXISTS Lexique;
DROP TABLE IF EXISTS Regex;
DROP TABLE IF EXISTS Tag_Projet;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Projets;
CREATE TABLE Projets
(
 id_projet INTEGER UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
 projet_name VARCHAR(20) UNIQUE NOT NULL,
 last_modif DATETIME
);

CREATE TABLE Tags
(
 id_tag INTEGER UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
 label VARCHAR(20) UNIQUE NOT NULL,
 color VARCHAR(7) DEFAULT "#FFFFFF",
 CONSTRAINT color_len CHECK (LENGTH(color) = 7)
);

CREATE TABLE Tag_Projet
(
 id_tag INTEGER NOT NULL,
 id_projet INTEGER NOT NULL,
 active BOOLEAN DEFAULT True,
 PRIMARY KEY(id_tag, id_projet),
 FOREIGN KEY(id_projet) REFERENCES Projets(id_projet) ON DELETE CASCADE,
 FOREIGN KEY(id_tag) REFERENCES Tags(id_tag) ON DELETE CASCADE
);

CREATE TABLE Lexique
(
 mot VARCHAR(20) NOT NULL,
 id_tag INTEGER NOT NULL,
 /*ordre INTEGER DEFAULT 0,*/
 PRIMARY KEY(mot, id_tag),
 FOREIGN KEY(id_tag) REFERENCES Tags(id_tag)
);

CREATE TABLE Regex
(
 id_regex INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
 regex TEXT NOT NULL,
 description TEXT,
 id_tag INTEGER NOT NULL,
 /*ordre INTEGER DEFAULT 0,*/
 FOREIGN KEY(id_tag) REFERENCES Tags(id_tag) ON DELETE CASCADE
);
